
import numpy as np

def generate_identity_lattice(size: int = 33) -> np.ndarray:
    """
    Generate a 3D identity lattice (grid of RGB points).

    Args:
        size (int): Size of the cube edge (e.g., 33 for 33x33x33).

    Returns:
        np.ndarray: Shape (size*size*size, 3) where each row is an RGB coordinate.
    """
    # Create linearly spaced points from 0 to 1
    ticks = np.linspace(0.0, 1.0, size, dtype=np.float32)
    
    # Create meshgrid using 'ij' indexing (R, G, B order)
    # Note: LUTs usually iterate R fast or B fast.
    # DaVinci .cube standard:
    # "The data must be in the order: Red, Green, Blue.
    # The blue component varies fastest, then green, then red."
    # Wait, usually for .cube:
    # DOMAIN_MIN 0 0 0
    # DOMAIN_MAX 1 1 1
    # LUT_3D_SIZE 33
    # R0 G0 B0
    # R0 G0 B1
    # ...
    # So Blue varies fastest.
    
    # np.meshgrid order: if we do (r, g, b), 'ij' indexing gives r varying first?
    # Let's verify.
    # We want loops: for r in ... for g in ... for b in ...
    # So r is slowest, b is fastest.
    
    r, g, b = np.meshgrid(ticks, ticks, ticks, indexing='ij')
    
    # Stack and reshape
    # We want a list of points (N, 3)
    # The order in the file must be R varies SLOWEST.
    # So if we flatten, we want B to be adjacent in memory?
    # Actually, let's construct it explicitly to be safe.
    
    points = np.zeros((size * size * size, 3), dtype=np.float32)
    idx = 0
    for i in range(size):         # Red (Slowest)
        for j in range(size):     # Green
            for k in range(size): # Blue (Fastest)
                points[idx] = [ticks[i], ticks[j], ticks[k]]
                idx += 1
                
    return points

def export_to_cube(lattice: np.ndarray, filepath: str, size: int = 33) -> None:
    """
    Export the transformed lattice to a .cube file.

    Args:
        lattice (np.ndarray): Shape (N, 3) containing transformed RGB values.
        filepath (str): Output file path.
        size (int): LUT size (e.g. 33).
    """
    if lattice.shape[0] != size ** 3:
        raise ValueError(f"Lattice size {lattice.shape[0]} does not match N^3 for N={size}")

    with open(filepath, 'w') as f:
        f.write(f"TITLE Generated by HCGE\n")
        f.write(f"LUT_3D_SIZE {size}\n")
        f.write(f"DOMAIN_MIN 0.0 0.0 0.0\n")
        f.write(f"DOMAIN_MAX 1.0 1.0 1.0\n")
        
        # Write data points
        for i in range(lattice.shape[0]):
            r, g, b = lattice[i]
            # Ensure format is clean float
            f.write(f"{r:.6f} {g:.6f} {b:.6f}\n")

